name: Update Vidget Rosstrah

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:  

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: docker-compose up
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          DB_URI: ${{ secrets.DB_URI }}
          SOURCE_TABLE: ${{ secrets.SOURCE_TABLE }}
          TARGET_TABLE: ${{ secrets.TARGET_TABLE }}